### ISSUE TITLE
Assets not found when setting up new module

### ISSUE THREAD

**Issue by chateaux** [RWOverdijk/AssetManager#156]
I seem to be having a recurring issue with asset manager and it is likely a setting somewhere.

Here is an example:

I had my assets in ModuleA:

/ModuleA
- assets
     - scripts
         - script A
         - script B

I then realised that script B should be in module B, so I moved it:

/ModuleB
- assets
     - scripts
         - script B

I added the required settings to ModuleB.config:

    'asset_manager' => [
        'caching' => [
            'default' => [
                'cache'     => 'FilePath',
                'options' => [
                    'dir'   => 'public',
                ]
            ],
        ],
        'resolver_configs' => [
            'paths' => [
                __DIR__ . '/../assets'
            ]

        ],
    ],

And when I re-ran the script, it would not find the file in the new location.

I copied files back and forth between the two asset directories and after about 20 minutes it all started to work.

This makes me wonder, is there some kind of cache happening in the background?

Many thanks!

**Comment by Ocramius** [comment]
@chateaux I strongly suggest writing a small integration test against the asset resolver before checking this here with us: it is likely a weird caching issue.

**Comment by RWOverdijk** [comment]
The only caching I can see is the FilePath cache. This doesn't have a TTL so the 20 minute thing sounds very unlike. Perhaps you have a config cache enabled, which would cache these settings. Otherwise it's very strict caching elsewhere, regardless of the origin, its somewhere in your own code.

I hope this helps. I'm going to close this issue now, but if the problem persists please don't hesitate to comment on this issue.
