### ISSUE TITLE
Proper way for role based access on assets?

### ISSUE THREAD

**Issue by laniakea** [RWOverdijk/AssetManager#181]
Hi there,
I'm pretty new and couldn't find an answer for my question. I want to use RBAC and assetmanager in a rest architecture. I'm using angularjs and I have html templates for every role, admin, guest etc. Could you please answer my question:
-Is it right to put my html templates in my assets folder?
-If so, how can I restrict them so for example only admin can load a specific file admin.html file?
I was thinking for the urls I probably can restrict the access. Sorry if my question is not relevant. It's just confusing for me.

**Comment by RWOverdijk** [comment]
Hello @laniakea and welcome :)

In your case, I'd say that your views should be behind controllers in order to restrict access. If you really wish to use this module to do that for you, you can create a resolver with a higher priority that decides whether or not a user has access to a particular file.

Personally, I don't think this is a good idea. I'd make all my html files public and make the data (RESTful backend) restricted in stead. Nobody can get any value from looking into admin templates; because there isn't (shouldn't be) any data in them.

**Comment by laniakea** [comment]
Thanks I see. Glueing RBAC, Doctrine, apigility and angularjs seems kind of impossible to me as I can't find enough documentation about it! I found this:
https://github.com/remiq/apigility-zfc-rbac-recipe
But is's far from a tutorial and my application is set up differently.

**Comment by RWOverdijk** [comment]
@laniakea In that case I don't think we'll be able to help you out on this ticket. But feel free to [hire us](http://spoonx.nl/contact) :)
