### ISSUE TITLE
Prefix path

### ISSUE THREAD

**Issue by stormfly-pl** [RWOverdijk/AssetManager#182]
Hi,
I use FilePathCache but there is a problem. I would like to all cache files go to folder assets/ where I set 777 permissions.

So i can put in configuration sth like:

```
'asset_manager' => array(
        'resolver_configs' => array(
            'map' => array(
                'assets/my-great-module/js/sth.min.js' => __DIR__ . '/../public/js/plugins/sth.js',
```

and it is great! But I have some modules from vendor where I've got:

```
'asset_manager' => array(
        'resolver_configs' => array(
            'map' => array(
                'datagrid-integration-module/js/jqx.min.js' => __DIR__ . '/../public/js/plugins/jqxwidgets/jqx-all.js',
```

there is no 'assets/' on the begining, so i can not use in view 'assets/datagrid-integration-module/js/jqx.min.js' because it won't be matched in the configuration file.

When I use 'datagrid-integration-module/js/jqx.min.js' AssetManager will always route the request through zf2 because the cached files are in the 'assets/datagrid-integration-module/' instead of 'datagrid-integration-module/'. I don't want to keep the static files in the 'datagrid-integration-module', but always in the 'assets/' (e.g. because the 'assets' is writeable, while 'datagrid-integration-module' is not). 

I think tha there's an easy way this can be fixed - if we add new key in config like "path_prefix" => "assets/"

and in AssetManager.php:

```
protected function resolve(RequestInterface $request)
{
// ...
        $uri        = $request->getUri();
        $fullPath   = $uri->getPath();
        $path       = substr($fullPath, strlen($request->getBasePath()) + 1);
        if (!empty($this->config['path_prefix']) && is_string($this->config['path_prefix'])) {
            if (substr($path, 0, strlen($this->config['path_prefix'])) == $this->config['path_prefix']) {
                $path = substr($path, strlen($this->config['path_prefix']));
            }
        }
        $this->path = $path;
```

Now we have great work static file cache.

What do you think about this solution? Thanks.

**Comment by RWOverdijk** [comment]
I'm not entirely sure what your question is... But it's possible to add the `/assets` path to your config and simply map it to `datagrid-integration-module/`.

**Comment by stormflypl** [comment]
My question is can you add new feature ( add "path_prefix" and handle it ). I will try to explain it in more detail.


config/autoload/global.php

```
'asset_manager' => [
	'caching' => [
        'default' => [
            'cache'     => 'AssetManager\\Cache\\FilePathCache',
            'options' => [
                'dir' => 'public/', // public/assets/ after my "path"
            ],
        ],
    ],
    'resolver_configs' => [
        'map => [
            'assets/js/plugins/jquery/jquery.min.js' => '... sth ...'
            // ...
        ]
    ]
```


module/Admin/view/layout/layout.phtml

```
<?php echo $this->headScript()
	// from zf2 application
	->appendFile($this->basePath('assets/js/plugins/jquery/jquery.min.js'), 'text/javascript')
    ->appendFile($this->basePath('assets/js/plugins/jqueryui/jquery-ui.min.js'), 'text/javascript')
    ->appendFile($this->basePath('assets/js/plugins/bootstrap/bootstrap.min.js'), 'text/javascript')

	// from vendor/
    ->appendFile($this->basePath('assets/datagrid-integration-module/js/jqx.min.js'), 'text/javascript') ?>

```


vendor/sth/datagrid-integration-module/config/module.config.php

```

'asset_manager' => array(
    'resolver_configs' => array(
        'aliases' => array(
            'datagrid-integration-module/css/images/' => __DIR__ . '/../public/css/jqxwidgets/images/'
        ),
        'map' => array(
            'datagrid-integration-module/js/jqx.min.js' => __DIR__ . '/../public/js/plugins/jqxwidgets/jqx-all.js',
            'datagrid-integration-module/js/globalize.min.js' => __DIR__ . '/../public/js/plugins/jqxwidgets/globalize.js',
            'datagrid-integration-module/js/localization_pl-PL.min.js' => __DIR__ . '/../public/js/plugins/jqxwidgets/localization_pl-PL.js'
        ),
        'collections' => array(
            'datagrid-integration-module/css/jqx.min.css' => array(
                'jqxwidgets/jqx.base.css',
                'jqxwidgets/jqx.bootstrap.css'
            ),
        ),
        'paths' => array(
            __DIR__ . '/../public/css',
        ),
    ),
```

When the code below is executed for the first time, no file will be found in the path "assets/js/plugins/jquery/jquery.min.js". The request will go through zf2, configuration key will be found and file will be written to cache in path "assets/js/plugins/jquery/jquery.min.js". When we send request to the application for the second time it will take static file without running zf2 :


```
<?php echo $this->headScript()
	// from zf2 application
	->appendFile($this->basePath('assets/js/plugins/jquery/jquery.min.js'), 'text/javascript'))

```

Now from vendor module:

```
<?php echo $this->headScript()
	// from vendor/
	->appendFile($this->basePath('assets/datagrid-integration-module/js/jqx.min.js'), 'text/javascript'))

```

oops, it won't be found in the map key, because there is "assets" on begining. Let's try:

```
<?php echo $this->headScript()
	// from vendor/
	->appendFile($this->basePath('datagrid-integration-module/js/jqx.min.js'), 'text/javascript'))

```

Great! It was found. But... the cache will try to store it in datagrid-integration-module/ dir. No permissions! You have only assets/ directory to write stuff.

That's why i I give some example code how to patch asset manager. And new key "path_prefix", or better name maybe "path_key_prefix", and modify method "resolve" in class AssetManager. Then I can use:

```
<?php echo $this->headScript()
	// from vendor/
	->appendFile($this->basePath('assets/datagrid-integration-module/js/jqx.min.js'), 'text/javascript'))

```

The key will be found in map resolver, cache will write it to assets/ directory and second request will read static file without zf2.

I don't want to overwrite all keys in resolvers from vendor module configuration, because it is sad solution.

I've hope it is more clear now.

**Comment by RWOverdijk** [comment]
You can set the cache path in the config. If you tell it to store the assets in the `assets/` dir you should be good. https://github.com/RWOverdijk/AssetManager/wiki/Caching#filepath

**Comment by stormflypl** [comment]
I used cache path in assetic config, but for now forget about it. I will configure cache to store files in assets/ folder. Now I try :

1)

```
<?php echo $this->headScript()
    // from vendor/
    ->appendFile($this->basePath('assets/datagrid-integration-module/js/jqx.min.js'), 'text/javascript'))

```

It will give me 404 because there is no map key "assets/datagrid-integration-module/js/jqx.min.js" in configuration. The cache will never appear.

2)

```
<?php echo $this->headScript()
    // from vendor/
    ->appendFile($this->basePath('datagrid-integration-module/js/jqx.min.js'), 'text/javascript'))

```

It will generate cache but the second request will run zf2, because cache is stored in "assets/datagrid-integration-module/js/jqx.min.js", don't you agree?

**Comment by RWOverdijk** [comment]
Why can't you change the map? The map always maps to the asset. Where you store it is up to you. Where you link to it, is also up to you. Those don't have to be related to each other.

**Comment by stormflypl** [comment]
But this is not my module, it's from vendor. It should be posibile not to overwrite full assetic config. You know it is not a good solution. In new version they may change config and I will be forced every composer update to check if they didn't change assetic config.

**Comment by stormflypl** [comment]
I try ealier to set map but there is problem with images that are in css. It cannot found them, they are set by "aliases" key.

**Comment by RWOverdijk** [comment]
Sorry for the late reply. I had around 600 unread emails to plow through...

For starters, if they change the config, they could also change the location of the file. I don't think it's a fair point to worry about.

Either way, I still think that the fact you can overwrite their config, or supply a map of your own is sufficient in this case.

**Comment by stormfly-pl** [comment]
I overwrite configuration. So you can close issue. But in my opinion it is similar situation like in mod rewrite where you have got "RewriteBase". You can add path in every line or set one path on start.

anyway thank you for your time :+1:

**Comment by RWOverdijk** [comment]
Cheers! :)
